# Generated by Django 4.1 on 2022-11-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('github_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('blog', models.URLField()),
                ('public_repos', models.IntegerField()),
                ('public_gists', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_id', models.IntegerField(unique=True)),
                ('private', models.BooleanField()),
                ('description', models.TextField()),
                ('github_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.githubuser')),
            ],
        ),
    ]
